### ISSUE TITLE
Configuration for level and bubble miss when using handler with type=service

### ISSUE THREAD

**Issue by Koc** [symfony/MonologBundle#116]
```yml
monolog:
    channels: [grabber]
    handlers:
        grabber_file:
            type:     service
            id:       metal.grabbers.monolog.handler.doctrine_dbal
            level:    INFO # I cann't get this parameter inside my service
            channels: [grabber]
```
