### ISSUE TITLE
Suggestion: Allow 200 status code to exclude http codes

### ISSUE THREAD

**Issue by lampelk** [symfony/MonologBundle#458]
I have a health check which floods my logs and would like to exclude but it doesn't exclude these paths `/ping` and `/health` for `200` status code:

```
  monolog:
    handlers:
      main:
        type: fingers_crossed
        excluded_http_codes: [ 404, { 200: [ '^/ping', '^/health' ] } ]
```
