### ISSUE TITLE
how to make symfony2 writes log in prod mode?

### ISSUE THREAD

**Issue by mappedinn** [symfony/MonologBundle#76]
I would like to make symfony writes in the file app/logs in prod mode.
To do so, I changed the config of monolog in config_prod.yml

```
monolog:
    handlers:
        main:
            type:         fingers_crossed
            action_level: error
            handler:      nested
        nested:
            type:  stream
            path:  %kernel.logs_dir%/%kernel.environment%.log
            level: debug
```

But, not prod.log file is generated!

Since the log is produced in **dev** mode, I copied than the monolog config which is available in config_dev.yml to the config_prod.yml. This config is follows:

```
monolog:
    handlers:
        main:
            type:  stream
            path:  %kernel.logs_dir%/%kernel.environment%.log
            level: debug
        firephp:
            type:  firephp
            level: info
        chromephp:
            type:  chromephp
            level: info
```

But, still no prod.log is written in prod mode.

Is there any idea?

**For your information** , I am using symfony 2.3.11.
