### ISSUE TITLE
MonologBundle processor per handler

### ISSUE THREAD

**Issue by flip111** [symfony/MonologBundle#77]
Problem description:
The configuration option for processors per handler is not available.

Docs: http://symfony.com/doc/current/cookbook/logging/monolog.html#adding-a-session-request-token

> If you use several handlers, you can also register the processor at the handler level instead of globally.

Example: https://github.com/symfony/MonologBundle/blob/master/DependencyInjection/Configuration.php#L562

Error:

```
[Symfony\Component\Config\Definition\Exception\InvalidConfigurationException]
Unrecognized options "processors" under "monolog.handlers.main"
```

Config:

```
monolog:
    handlers:
        main:
            type:  stream
            path:  %kernel.logs_dir%/%kernel.environment%.log
            level: debug
            processors: [@monolog.processor.log]
```

Notice that no actual configuration option for "processors" can be found in the DI configuration.

Note: this is a copy of https://github.com/symfony/symfony/issues/10704
