### ISSUE TITLE
Make Monolog format configurable in Symfony 

### ISSUE THREAD

**Issue by james-bw** [symfony/MonologBundle#80]
I should be able to config the format of monolog simply, to be able to output for example class and method. This works, in that it does make the format as described int he arguments:

``` yaml
services:
    my_log_formatter:
        class: Monolog\Formatter\LineFormatter
        arguments: ["[%%datetime%%] %%channel%%.%%level_name%%: %%message%% %%context%% %%extra%%\n"]

monolog:
    handlers:
        file:
            type: stream
            level: debug
            formatter: my_log_formatter
```

...but trying to add %O (class) or %M (method) to the arguments, which are supported by Monolog, does not configure the logger format.
