### ISSUE TITLE
channel filtering

### ISSUE THREAD

**Issue by hgraca** [symfony/MonologBundle#83]
Hi,

I usually use channel filtering in my logging and I just started a new project and noticed that the channels filtering is not working.

Symfony version: ~2.4
Monolog version: 1.10.x-dev (the default for symfony 2.4)

in my config_dev.yml I have this:

``` yml
monolog:
    handlers:
        main:
            type:     group
            channels: ["app", "doctrine", "!event"]
            members:  [streamed, console]
        streamed:
            type:  stream
            path:  "%kernel.logs_dir%/%kernel.environment%.log"
            level: debug
        console:
            type:   console
            verbosity_levels:
                VERBOSITY_NORMAL: INFO
            level:      debug
```

I'm getting "event.DEBUG" and "request.INFO" in my logs, although I've set it to log only app and doctrine stuff and explicitly excluded event.
Did something changed? Am I doing something wrong? Or is this a bug?

Tkx
